// Copyright 2023 @ipetepete
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#define QUICK_TAP_TERM 0
#define TAPPING_TERM 150
//#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD
#define TAPPING_TERM_PER_KEY
#define ONESHOT_TAP_TOGGLE 10
#define ONESHOT_TIMEOUT 600
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#ifdef HOLD_ON_OTHER_KEY_PRESS
#undef HOLD_ON_OTHER_KEY_PRESS
#endif

#ifdef POINTING_DEVICE_ENABLE
# define CIRQUE_PINNACLE_TAP_ENABLE
# define CIRQUE_PINNACLE_POSITION_MODE  CIRQUE_PINNACLE_ABSOLUTE_MODE
# define CIRQUE_PINNACLE_ATTENUATION_4X
# define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
//# define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
#endif

#ifndef __ASSEMBLER__
#  include "wrappers.h"
#endif
